title: "Union of Grinnell Student Dining Workers"
description: "The only independent undergraduate labor union in the country, UGSDW fights for fair pay and benefits for workers at Grinnell College."
url: "https://www.ugsdw.org"

permalink: pretty

collections:
    - petitions

defaults:
    -
        scope:
            path: ""
        values:
            layout: default
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: petitions
        values:
            layout: petition


exclude: [links.jsonp]
sass:
    style: compressed
    sass_dir: ./css

gems:
    - jekyll-sitemap

prose:
    rooturl: "_posts"
    siteurl: "https://ugsdw.github.io/"
    relativeLinks: "https://usgdw.github.io/links.jsonp"
    media: "assets/news"
    metadata:
        _posts:
            - name: "title"
              field:
                  element: "text"
                  label: "Title"
                  value: ""
            - name: "author"
              field:
                  element: "text"
                  label: "Author"
                  value: ""
