title: "Union of Grinnell Student Dining Workers"
description: "The only independent undergraduate labor union in the country, UGSDW fights for fair pay and benefits workers at Grinnell College."
url: "https://ugsdw.github.io"

baseurl: /
permalink: pretty

defaults:
    -
        scope:
            path: ""
        values:
            layout: default

exclude: [links.jsonp]
sass:
    style: compressed

prose:
    rooturl: "_posts"
    siteurl: "https://ugsdw.github.io/"
    relativeLinks: "https://usgdw.github.io/links.jsonp"
    media: "media"
    metadata:
        _posts:
            - name: "category"
              field:
                  element: "hidden"
                  value: "blog"
            - name: "layout"
              field:
                  element: "hidden"
                  value: "blog"
            - name: "title"
              field:
                  element: "text"
                  label: "Title"
                  value: ""
                  _posts/static:
                      - name: "layout"
                        field:
                            element: "hidden"
                            value: "page"
                      - name: "title"
                        field:
                            element: "text"
                            label: "Title"
                            value: ""
                      - name: "permalink"
                        field:
                            element: "text"
                            label: "Permalink"
                            value: ""
